// <auto-generated />
using System;
using LuckyFridayCalculator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuckyFridayCalculator.Migrations
{
    [DbContext(typeof(LuckyFridayDbContext))]
    [Migration("20251117185149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuckyFridayCalculator.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Account 1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Account 2"
                        });
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.Friday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BetDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dog")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalDeposit")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalOddsHongKong")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("TotalOddsInternational")
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Fridays", t =>
                        {
                            t.HasCheckConstraint("CK_Friday_TotalDeposit", "[TotalDeposit] > 0 AND [TotalDeposit] < 8100000");
                        });
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.HedgeSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("FridayId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FridayId")
                        .IsUnique();

                    b.ToTable("HedgeSets");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.LineupEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("FridayId")
                        .HasColumnType("int");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FridayId");

                    b.HasIndex("MemberId");

                    b.ToTable("LineupEntries");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.SingleBet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FridayId")
                        .HasColumnType("int");

                    b.Property<int?>("HedgeSetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MatchStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OddsHongKong")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal>("OddsInternational")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("FridayId");

                    b.HasIndex("HedgeSetId");

                    b.ToTable("SingleBets");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.Friday", b =>
                {
                    b.HasOne("LuckyFridayCalculator.Models.Account", "Account")
                        .WithMany("Fridays")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.HedgeSet", b =>
                {
                    b.HasOne("LuckyFridayCalculator.Models.Friday", "Friday")
                        .WithOne("HedgeSet")
                        .HasForeignKey("LuckyFridayCalculator.Models.HedgeSet", "FridayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Friday");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.LineupEntry", b =>
                {
                    b.HasOne("LuckyFridayCalculator.Models.Friday", "Friday")
                        .WithMany("LineupEntries")
                        .HasForeignKey("FridayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LuckyFridayCalculator.Models.Member", "Member")
                        .WithMany("LineupEntries")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Friday");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.SingleBet", b =>
                {
                    b.HasOne("LuckyFridayCalculator.Models.Friday", "Friday")
                        .WithMany("SingleBets")
                        .HasForeignKey("FridayId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("LuckyFridayCalculator.Models.HedgeSet", "HedgeSet")
                        .WithMany("SingleBets")
                        .HasForeignKey("HedgeSetId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Friday");

                    b.Navigation("HedgeSet");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.Account", b =>
                {
                    b.Navigation("Fridays");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.Friday", b =>
                {
                    b.Navigation("HedgeSet");

                    b.Navigation("LineupEntries");

                    b.Navigation("SingleBets");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.HedgeSet", b =>
                {
                    b.Navigation("SingleBets");
                });

            modelBuilder.Entity("LuckyFridayCalculator.Models.Member", b =>
                {
                    b.Navigation("LineupEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
